<?php
declare(strict_types=1);
require_once __DIR__ . '/../session-security.php'; session_start(); sessionSecurityEnforce();
require_once __DIR__ . '/../auth.php'; require __DIR__ . '/banco.php';
if(!authLogged()){header('Location: index.php');exit;} $pdo=db(); if(!authPermission($pdo,'app.mapa')){http_response_code(403);die('Sem permissão.');}
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Possíveis alunos duplicados</title><style>
*{box-sizing:border-box}body{margin:0;background:#f5f8fc;color:#172033;font:14px system-ui,-apple-system,Segoe UI,sans-serif}.top{background:#075fae;color:#fff;padding:18px 24px}.topin{max-width:1280px;margin:auto;display:flex;align-items:center;gap:16px}.back{color:#fff;text-decoration:none;font-weight:800}.wrap{max-width:1280px;margin:24px auto;padding:0 18px}.head{display:flex;justify-content:space-between;gap:16px;align-items:end;margin-bottom:18px}.head h1{margin:0 0 5px;font-size:24px}.muted{color:#64748b}.controls{display:flex;gap:10px;flex-wrap:wrap}.controls input,.controls select{height:42px;border:1px solid #cbd5e1;border-radius:10px;padding:0 12px;background:#fff}.btn{border:0;border-radius:10px;padding:11px 14px;font-weight:800;cursor:pointer}.primary{background:#075fae;color:#fff}.pair{background:#fff;border:1px solid #dce5f0;border-radius:16px;margin:0 0 14px;overflow:hidden}.why{padding:10px 16px;background:#f8fafc;border-bottom:1px solid #e5eaf1;display:flex;justify-content:space-between;gap:10px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:0}.person{padding:16px}.person:first-child{border-right:1px solid #e5eaf1}.name{font-size:17px;font-weight:850;margin-bottom:8px}.badge{display:inline-block;border-radius:999px;padding:4px 8px;background:#eef6ff;color:#075fae;font-weight:800;font-size:12px}.keep{background:#ecfdf3;color:#087443}.stats{display:flex;gap:8px;flex-wrap:wrap;margin:10px 0}.stat{background:#f8fafc;border:1px solid #e5eaf1;border-radius:9px;padding:7px 9px}.actions{padding:12px 16px;border-top:1px solid #e5eaf1;display:flex;justify-content:flex-end;gap:10px;align-items:center}.merge{background:#0f766e;color:#fff}.empty{background:#fff;border:1px dashed #cbd5e1;padding:40px;text-align:center;border-radius:14px}.details{font-size:12px;color:#64748b;line-height:1.55}.danger{color:#b42318;font-weight:700}@media(max-width:700px){.grid{grid-template-columns:1fr}.person:first-child{border-right:0;border-bottom:1px solid #e5eaf1}.head{align-items:stretch;flex-direction:column}}
</style></head><body><div class="top"><div class="topin"><a class="back" href="index.php">← Mapa</a><strong>Possíveis alunos duplicados</strong></div></div><main class="wrap"><div class="head"><div><h1>Identificação de duplicados</h1><div class="muted">Compara nomes ignorando acentos e pequenas variações. Nenhum cadastro é mesclado sem confirmação.</div></div><div class="controls"><input id="q" placeholder="Buscar nome..."><select id="f"><option value="todos">Todos</option><option value="100">Somente correspondência exata</option><option value="aprox">Somente semelhantes</option></select><button class="btn primary" id="reload">Atualizar</button></div></div><div id="status" class="muted">Analisando cadastros...</div><div id="list"></div></main><script>
const API='duplicados_api.php';let pares=[];const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function vinc(x){const v=x.vinculos||{};return Object.entries(v).filter(([,n])=>n>0).map(([k,n])=>`${k.replaceAll('_',' ')}: ${n}`).join(' • ')||'Sem vínculos adicionais';}
function card(p){const principal=p.a.score>=p.b.score?p.a:p.b,sec=principal.id===p.a.id?p.b:p.a;const person=(x,isKeep)=>`<div class="person"><div class="name">${esc(x.nome)}</div><span class="badge ${isKeep?'keep':''}">${isKeep?'✓ Sugerido como principal':'Será incorporado ao principal'}</span><div class="stats"><span class="stat"><b>#${x.id}</b></span><span class="stat"><b>${x.score}</b> pontos de histórico</span><span class="stat"><b>${x.campos}</b> campos preenchidos</span></div><div class="details">Documento: ${esc(x.documento||'—')}<br>Telefone: ${esc(x.telefone||'—')}<br>E-mail: ${esc(x.email||'—')}<br>Última presença: ${esc(x.ultima_presenca||'—')}<br>${esc(vinc(x))}</div></div>`;return `<article class="pair" data-name="${esc((p.a.nome+' '+p.b.nome).toLowerCase())}" data-sim="${p.similaridade}"><div class="why"><b>${esc(p.motivo)}</b><span>${p.similaridade}% de similaridade</span></div><div class="grid">${person(principal,true)}${person(sec,false)}</div><div class="actions"><span class="muted">Será mantido o cadastro #${principal.id}, que possui mais informações.</span><button class="btn merge" data-a="${principal.id}" data-b="${sec.id}">Mesclar alunos</button></div></article>`}
function render(){const q=document.querySelector('#q').value.trim().toLowerCase(),f=document.querySelector('#f').value;const arr=pares.filter(p=>(!q||(p.a.nome+' '+p.b.nome).toLowerCase().includes(q))&&(f==='todos'||(f==='100'?p.similaridade===100:p.similaridade<100)));document.querySelector('#list').innerHTML=arr.length?arr.map(card).join(''):'<div class="empty">Nenhum possível duplicado encontrado com este filtro.</div>';document.querySelector('#status').textContent=`${arr.length} possível(is) duplicidade(s) exibida(s).`;document.querySelectorAll('.merge').forEach(b=>b.addEventListener('click',()=>merge(+b.dataset.a,+b.dataset.b,b)));}
async function load(){document.querySelector('#status').textContent='Analisando cadastros...';document.querySelector('#list').innerHTML='';try{const r=await fetch(API+'?action=listar',{cache:'no-store'});const j=await r.json();if(!j.ok)throw Error(j.error||'Erro');pares=j.pares||[];render()}catch(e){document.querySelector('#status').innerHTML='<span class="danger">'+esc(e.message)+'</span>'}}
async function merge(a,b,btn){if(!confirm(`Mesclar os cadastros #${a} e #${b}?\n\nO sistema manterá automaticamente o cadastro com mais histórico e transferirá os vínculos do menor para ele.`))return;btn.disabled=true;btn.textContent='Mesclando...';try{const r=await fetch(API+'?action=mesclar',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id1:a,id2:b})});const j=await r.json();if(!j.ok)throw Error(j.error||'Não foi possível mesclar.');alert(`Concluído. Cadastro #${j.principal_id} mantido; #${j.incorporado_id} incorporado.`);await load()}catch(e){alert(e.message);btn.disabled=false;btn.textContent='Mesclar alunos'}}
document.querySelector('#q').addEventListener('input',render);document.querySelector('#f').addEventListener('change',render);document.querySelector('#reload').addEventListener('click',load);load();
</script></body></html>
