<?php
declare(strict_types=1);require_once __DIR__.'/../session-security.php';session_start();sessionSecurityEnforce();require_once __DIR__.'/../auth.php';if(!authLogged()){header('Location: ../mapa/');exit;}
?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Central WhatsApp • Liceu</title><style>
*{box-sizing:border-box}body{margin:0;font-family:Inter,Arial,sans-serif;background:#f5f7fa;color:#172033}.top{height:64px;background:#075ca8;color:#fff;display:flex;align-items:center;padding:0 22px;gap:18px}.top img{height:34px}.top b{font-size:18px}.top a{margin-left:auto;color:#fff;text-decoration:none;background:#ffffff18;padding:9px 12px;border-radius:9px}.wrap{max-width:1450px;margin:auto;padding:22px}.hero{display:flex;justify-content:space-between;gap:16px;align-items:flex-end}.hero h1{margin:0}.muted{color:#6b7b8d;font-size:13px}.grid{display:grid;grid-template-columns:repeat(5,1fr);gap:10px;margin:18px 0}.kpi,.card{background:#fff;border:1px solid #e2e8f0;border-radius:13px;padding:15px}.kpi strong{display:block;font-size:24px;color:#075ca8}.kpi span{font-size:12px;color:#64748b}.layout{display:grid;grid-template-columns:1.2fr 1fr;gap:14px}.head{display:flex;justify-content:space-between;align-items:center;gap:10px;margin-bottom:12px}.btn{border:0;border-radius:9px;padding:9px 12px;font-weight:800;cursor:pointer}.primary{background:#075ca8;color:#fff}.ghost{background:#eef4fa;color:#075ca8}.danger{background:#fee2e2;color:#991b1b}.ok{background:#dcfce7;color:#166534}.warn{background:#fef3c7;color:#92400e}.pill{display:inline-flex;padding:5px 8px;border-radius:999px;font-size:11px;font-weight:900}input{border:1px solid #cbd5e1;border-radius:9px;padding:9px}.table{width:100%;border-collapse:collapse}.table th,.table td{text-align:left;padding:9px;border-bottom:1px solid #edf2f7;font-size:12px}.table th{color:#64748b;font-size:10px;text-transform:uppercase}.scroll{max-height:560px;overflow:auto}.msg{padding:10px;border-bottom:1px solid #edf2f7}.msg b{font-size:12px}.msg p{margin:5px 0;font-size:12px}.statusbox{margin:14px 0;padding:12px;border-radius:11px;background:#f8fafc;border:1px solid #e2e8f0}.actions{display:flex;gap:8px;flex-wrap:wrap}@media(max-width:900px){.grid{grid-template-columns:repeat(2,1fr)}.layout{grid-template-columns:1fr}.wrap{padding:12px}}</style></head><body>
<div class="top"><img src="../logo-liceu.png" alt="Liceu"><b>💬 Central WhatsApp</b><a href="../mapa/">← Voltar ao Mapa</a></div><div class="wrap"><div class="hero"><div><h1>Atendimento e automações</h1><div class="muted">API oficial • faltosos • entrega/leitura • respostas recebidas por webhook</div></div></div><div class="grid" id="kpis"></div>
<div class="layout"><section class="card"><div class="head"><div><b>Faltosos do dia</b><div class="muted">Prepare a campanha antes de qualquer disparo.</div></div><input type="date" id="data"></div><div class="actions"><button class="btn ghost" onclick="carregarFaltosos()">Atualizar</button><button class="btn primary" onclick="preparar()">Preparar campanha</button><button class="btn primary" id="send" onclick="enviar()" disabled>Enviar pela API oficial</button></div><div class="statusbox" id="cfg">Carregando configuração...</div><div class="scroll"><table class="table"><thead><tr><th>Aluno</th><th>Turma</th><th>Telefone</th><th>Situação</th></tr></thead><tbody id="faltosos"></tbody></table></div></section>
<section class="card"><div class="head"><div><b>Últimas mensagens</b><div class="muted">Saídas, entregas, leituras e respostas.</div></div><button class="btn ghost" onclick="carregarConversas()">Atualizar</button></div><div class="scroll" id="msgs"></div></section></div></div><script>
const api='api.php';let campanhaId=0;const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function hoje(){let d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}document.getElementById('data').value=hoje();
async function lerJson(r){let t=await r.text(),j=null;try{j=t?JSON.parse(t):null}catch(_){throw Error('O servidor retornou uma resposta inválida (HTTP '+r.status+'). Verifique o log PHP do servidor.')}if(!j)throw Error('O servidor não retornou resposta (HTTP '+r.status+').');if(!r.ok||j.ok===false)throw Error(j.error||('Erro HTTP '+r.status));return j}async function get(a){let r=await fetch(api+'?'+a,{credentials:'same-origin',cache:'no-store'});return lerJson(r)}async function post(a,b){let r=await fetch(api+'?action='+a,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});return lerJson(r)}
async function status(){try{let j=await get('action=status'),k=j.kpis,c=j.config;document.getElementById('kpis').innerHTML=[['Registros',k.total],['Enviados',k.enviados],['Entregues',k.entregues],['Lidos',k.lidos],['Respostas',k.respostas]].map(x=>`<div class="kpi"><strong>${x[1]}</strong><span>${x[0]} • 30 dias</span></div>`).join('');document.getElementById('cfg').innerHTML=c.pronto?`<span class="pill ok">API pronta</span> Template: <b>${esc(c.templateFalta)}</b>`:`<span class="pill warn">Modo configuração</span> Ainda falta configurar no servidor: <b>${esc(c.faltando.join(', '))}</b>. Nenhum disparo será feito enquanto isso.`;document.getElementById('send').disabled=!c.pronto||!campanhaId}catch(e){document.getElementById('cfg').textContent=e.message}}
async function carregarFaltosos(){try{let d=document.getElementById('data').value,j=await get('action=faltosos&data='+encodeURIComponent(d));document.getElementById('faltosos').innerHTML=j.faltosos.map(x=>`<tr><td><b>${esc(x.aluno)}</b></td><td>${esc(x.turma)}</td><td>${esc(x.telefone||'—')}</td><td>${x.podeEnviar?'<span class="pill ok">Pronto</span>':'<span class="pill danger">Sem telefone</span>'}</td></tr>`).join('')||'<tr><td colspan="4">Nenhum faltoso registrado nesta data.</td></tr>'}catch(e){alert(e.message)}}
async function preparar(){try{let j=await post('preparar_faltosos',{data:document.getElementById('data').value});campanhaId=j.campanhaId;alert(j.mensagem+' Total: '+j.total);await status();await carregarConversas()}catch(e){alert(e.message)}}async function enviar(){if(!campanhaId)return;if(!confirm('Enviar agora a campanha preparada pela API oficial do WhatsApp?'))return;try{let j=await post('enviar_campanha',{campanhaId});alert('Enviados: '+j.enviados+' • Erros: '+j.erros);await status();await carregarConversas()}catch(e){alert(e.message)}}
async function carregarConversas(){try{let j=await get('action=conversas');document.getElementById('msgs').innerHTML=j.mensagens.map(m=>`<div class="msg"><b>${m.direcao==='entrada'?'⬅️':'➡️'} ${esc(m.aluno||m.telefone)}</b> <span class="pill ${m.direcao==='entrada'?'ok':'ghost'}">${esc(m.status)}</span><p>${esc(m.corpo||'')}</p><div class="muted">${esc(m.criado_em||'')}</div></div>`).join('')||'<div class="muted">Nenhuma mensagem registrada ainda.</div>'}catch(e){document.getElementById('msgs').textContent=e.message}}
status();carregarFaltosos();carregarConversas();setInterval(()=>{status();carregarConversas()},30000);
</script></body></html>
